src/CMakeLists.txt
src/reactor.cc
src/reactor.h
src/reactor_tests.cc

~~This isn't 100% ready, but it is functional and nearly complete.  Still needs a bit more annotations and a few tests but otherwise done.~~ (done now)  After some discussion with @gidden and a bit with Paul, we decided that any continuous batch/assembly mode would not work well - and would likely provide poor results in analysis.  One consequence of this is that the new Reactor will not be able to exactly match the physor regression/integration results.  However, I tweaked the 1_enrichment_2_reactors input file to have 10 0.1kg assemblies in the core instead of 1 1kg assembly - and the results rounded to the nearest integer are in perfect agreement.
What do we want to do for testing?
I also added a nifty ReactorEvents table that records things like cycle start, cycle end, discharging, …

New Reactor facility

---

src/deploy_inst.cc
src/deploy_inst_tests.cc

deploy inst was previously causing many duplicate entries in the output db for a single prototype.  This fixes that.

fix duplicate prototype entries in db

---

src/source.h

Just need to remove extra prefix indent that causes funny rendering in restructuredtext.

fix source facility note annotation

---

src/reactor.cc
src/reactor.h
src/reactor_tests.cc

* discharge all fuel fuel from core at end of life (and transmute it).
* if nearing end of life, only order up to enough fresh fuel to reach end of life.
* block decommissioning until all fuel has been removed from core and traded away out of spent inventory.
Note that testing this will require an adjustement to MockSim.  This helps results for FCO related analysis significantly.

Handle reactor retirement better:

---

src/deploy_inst.h
src/enrichment.h
src/fuel_fab.h
src/reactor.h
src/separations.h
src/sink.h
src/source.h

Goal was to reorganize pragma variables so they will show up consistently and logically in Cycic.  For some reason I was unable to load some archetypes into Cyclist, so feel free to suggest/PR other ordering if desired.  Full list of changes is:
- Pragma variables were reorganized to show up consistently in Cyclist.  Code was shuffled but not removed.  
- One uilabel error was corrected (in reactor.h).  
- All pragma variables were confirmed to have uilabels, with the exception of ResBuf pragmas, which are invisible to the user.  
- Some formatting was done to keep to the 80 character line limit.  
- A couple of typos corrected.
Unit tests, nosetests, and run_inputs all pass on Mac.

Check vars

---

src/enrichment.cc
src/enrichment_tests.cc

Addresses bug reported by Jenny in which EF facility only trades one unit of tails commodity at each time step, even if the quantity does not meet the requested quantity.  Includes a test.  Jenny can you confirm this PR works for your use case?

Fix EF tails

---

src/reactor.cc
src/reactor_tests.cc

Previously, reactors would fail to record their last entry in TimeSeriesPower
table due to retirement guards that prevented the code from executing.  This
fixes that.  There may still be a corner case that isn't handled quite right
if a reactor's refueling cycle ends exactly on the time step that it retires,
but I'm not sure.
When a reactor approaches retirement, it reduces its fuel ordering to only
acquire enough to last until retirement.  Previously, this didn't account for
the reactor potentially being short on fuel (i.e. the core wasn't full) and so
could under-order fresh fuel in certain circumstances.  This has been fixed.

Fix bugs relating to reactor retirement:

---

src/separations.cc
src/separations.h
src/separations_tests.cc

* Refuse to decommission until all separated stream buffers are empty
* Stop requesting new material if there is enough to satisfy throughput until
end-of-life
... still needs tests - coming later.

Better end-of-life behavior for separations:

---

src/separations.cc

In some case, separation was making bid with a 0 quantity, which cause some problem for the cyclus Greedy solver.

prevent separation to make bid with 0 quantity

---

install.py

change the existing flag `--replace` to` --clean-build` to match the Cyclus installation flag.

installation flag uniformisation between cyclus and cycamore

---

src/separations.cc
src/separations_tests.cc

Throw an error when defining a total separation efficiency greater than 1 for a nuclei.

Limit the total separation efficiency per nuclei

---

src/enrichment.cc

Drew found that a <= condition was failing on the = (though it had passed in the unit test).

max enrich condition was sometimes failing due to floating point errors

---

src/mixer.h

This fixes an error in the Cycic annotations for the Mixer archetype

Fix units of buf_size to match shape expected/required by cycic

---

src/enrichment.cc
src/fuel_fab.cc
src/mixer.cc
src/separations.cc
src/storage.cc

According to [the discussion about floating point issues](https://groups.google.com/forum/#!topic/cyclus-dev/d25nGI9dYH0):
changing all `Pop` call in Cycamore to `Pop(qty, eps)`.
The eps used is the `cyclus::eps_rsrc()`, and is by default 1e-6.

Absolute precision

---

src/CMakeLists.txt

this is linked to cyclus PR [#1270](https://github.com/cyclus/cyclus/pull/1270), and to solve cycamore issue #419.
This solution prevent header file from cycamore to be installed (theoretically only cyclus header file should be require by developers...)
(Alternatively on can argues that Cycamore header file could be useful for developers, to develop news modules against Cycamore.)

fix header collision when installing cycamore

---

src/mixer.cc
src/mixer.h
src/mixer_tests.cc

This update the mixer API solving #421 issue.
This is a join PR with cyclus PR [#1271](https://github.com/cyclus/cyclus/pull/1271)
this update mixer API, to allows multiple commodity requests (with different preferences) for each streams that will be mixed i the facility.
The previous API did not deal multiple commodity requests for a single stream. And the previous API would have make it very difficult.
This need a new type: 
`std::vector<std::pair<std::pair<double, double>, std::map<std::string, double> > >`
which has been added in CYCLUS (see cyclus PR [#1271](https://github.com/cyclus/cyclus/pull/1271))
cycamore::mixer unit test have been updated as well.
The implement might not the best: I try to update the API as quick as possible, but the API is fine I think, allowing changing the …

Update mixer API

---

src/sink.cc
src/sink.h
src/sink_tests.cc
src/storage.cc

the release v1.4.0 is not tolerant to pref 0. 
Apparently sink use to do 0 preference request (by default), which stop the simulation...
this should fix it and put everything back to normal.
If you could review it quickly, I think it should go in the 1.4.2 release.... :(
@scopatz @gonuke @FlanFlanagan

fix sink default pref

---

src/enrichment.h
src/reactor.h

Updated metadata for enrichment.h and reactor.h:
Enrichment: added range to max_enrich [0.0, 1.0] and to tails_assay [0.0,0.003]
Reactor: added default values to cycle_time, n_assem_core, n_assem_fresh, and refuel_time these are subject to change in later updates.

updated metadata

---

src/reactor.h

@scopatz @aglenn2 :
I fix the cycamore unit test by re-setting the minimum fresh assembly to 0
the change from 0 to 3 definitely change the behavior of the reactor... and as most of the cycamore user don't specify it... I think this is better to actually keep it that way...

Fix cycamore_unit_test

---

input/enrichment/1_src_enr_rxtr_sink.xml
input/enrichment/linear_src_enr_rxtr_sink.xml
input/enrichment/natu_capacitated.xml
input/enrichment/swu_capacitated.xml
src/enrichment.cc
src/enrichment.h
src/enrichment_tests.cc
tests/test_regression.py

this PR fix the calculation of the enrichment:
this now requires the proper amount of feed material and calculate the proper enrichment of the tails.
the unit test have been updated accordingly.
the precedent issue was a confusion when calculating the feed quantity required using the mass quantity and the atom enrichment fraction. 
this now use mass enrichment fraction for everything.

fix enrichement calculation

---

CMakeLists.txt

Needed after https://github.com/cyclus/cyclus/pull/1443 goes in.

corresponding fix for cyclus ncrb

---

src/reactor.cc
src/reactor.h
src/reactor_tests.cc

I have added additions to the `cycamore::Reactor` so that it can also produce side products (e.g. steam, process heat, etc) when it produces power.
This is a completely optional parameter and won't cause errors to current users if they do not use this. But it gives the users ability to model hybrid nuclear reactor systems that do desalination or have other by-products.

Reactor by-product

---

src/reactor.cc
src/reactor.h
src/separations.cc
src/separations.h

This PR adds two backwards-compatible functions:
1. Cycamore::Reactor has an additional boolean - if true, the reactor will transmute all its assemblies to the depleted recipe upon decommission
2. Cycamore:Separations will write to the output its throughput and the streams it created.

Optional decom behavior and separations data record

---

src/reactor.cc
src/storage.cc

In this PR: 
Recordtimeseries of supply of spent fuel is moved from `Reactor::GetMatlTrades()` to `Reactor::Discharge()`. This was done because the `timeseriessupplyspentfuel` table currently only shows up in the output database if the commodity is traded. However, we need to know how much of that commodity is in the spent buffer and available for trade. 
This is used in d3ploy so that it can know how many of the other facilities need to be deployed to receive the commodity.

reactor recordtimeseries supply of spent fuel

---

src/reactor_tests.cc

resolves issue #488 unit test segfault by using "std::string" in a Cond function call within the MultipleByProduct reactor test. probably something to do with boost.

fixes unit test segfault

---

src/reactor.cc

This pr addresses https://github.com/arfc/d3ploy/issues/196

timeseriessupplypower does not record until the reactor produces power.

---

.gitignore
src/reactor.cc
src/reactor_tests.cc

This fix prevents that a new fuel cycle wrongfully starts in cycamore::Reactor.
Consider a reactor whose core cannot be discharged due to a full spent
fuel inventory. The if-statement that checks whether or not a new
fuel cycle is about to be initiated does not take into account if the 
core has been discharged: it only considers if the core is full.
Hence, it is possible that power is generated despite the core being
composed (partially or entirely) of spent fuel.
This behaviour has been explained further in 9c3e52468b6c59db4793c8e630317c04063ce6a9 and it has been fixed
by explicitly checking if the core has been discharged.
Moreover, b9935ff0b4eccaee31c33c8fc7c3e6c1a2d59cec adds a test to check this.

Prevent incorrect start of a new fuel cycle in Reactor

---

src/enrichment.h

More than once now, I've forgotten to include a recipe in my request for the product commodity from cycamore enrichmentt, and then been confused why my enrichment facility is not trading material. This adds a sentence to the docs with a gentle reminder that a request for the product commod is not enough; the request must also have an associated recipe

add sentence about request to Enrichment requiring recipe

---

src/storage.cc
src/storage.h

Adds optional variable `sell_quantity` to Storage archetype. Facility must have >= `sell_quantity` in the buffer to sell material, and only trades in integer multiples of `sell_quantity`
Requires [Cyclus PR #1552](https://github.com/cyclus/cyclus/pull/1552) to work as intended.
cc @bam241

Add Sell quantity to storage

---

src/reactor.cc

The reactor records initial demand (t=0) as a series of individual demands equal to the number of assemblies in the core plus fresh assemblies requested to keep on hand. However an error meant that the mass request associated with each each assembly demand was equal to the core + fresh assembly mass
E.g. a reactor with 3 assemblies in the core plus 1 on hand, each 1 kg, would previously record 4 separate requests for 3 kg at t=0. After this PR, it will correctly issue 4 separate requests for 1 kg each.
This keeps each individual request to the correct mass of `assem_size`
Closes #514, thanks @danielwojtaszek for already having an issue open when I stumbled upon this myself

fix recorded reactor initial demand

---

src/storage.cc
src/storage.h

- Adds `ready` buffer to current_capacity calculation
- Adds a bit more logging on high verbosity (logging levels 4 and 5 especially)
Closes #541

Fix bug that can cause storage capacity to go negative

---

src/sink.cc
src/sink.h
src/sink_tests.cc

- Three new optional parameters to vary the size of the sink's request
- `random_size` has default None, but also ~~four~~ two options that call the PRNG from the context: 
- "UniformReal", "NormalReal"
- No longer implemented
- "UniformInt", "NormalInt"
- When using ~~one of~~ the normal distribution~~s~~, two additional parameters `random_size_mean` and `random_size_stddev` are used as fractions of the maximum request size (calculated at each timestep `RequestAmt()`)
Checklist
closes #556

add random behavior for size of sink request

---

src/storage.cc
src/storage.h
src/storage_tests.cc
src/storage_tests.h

Implement the active and dormant buy policy periods (relies on Cyclus PR [#1596](https://github.com/cyclus/cyclus/pull/1596)) in Storage
Don't merge until the underlying Cyclus PR is merged (tests won't pass until then, anyway)

optional active and dormant buying periods in Storage

---

.github/workflows/changelog_test.yml
CHANGELOG.rst

Copied the workflow from cyclus and modified to fit cycamore.  Also added the last few PRs to the CHANGELOG (since the first one I made), do we need to go back and fill in old changes?
Fixes #561

Add CHANGELOG test workflow

---

.github/workflows/build_test.yml
.github/workflows/build_test_publish.yml
CHANGELOG.rst

Push new images on all pushes to main, so that they can be used in downstream testing (e.g. Cymetric)
Fixes #563

Publish docker images on all pushes to main

---

CHANGELOG.rst
src/sink.cc
src/sink.h
src/sink_tests.cc

Adds randomness in the next time Sink requests material through `random_frequency_type`. Options:
- `UniformInt`, which also requires `random_frequency_max` (otherwise the default is 1e299, making it extremely unlikely that the facility ever gets called), and optional `random_frequency_min`, which has a default of 1
- `NormalInt` which has `random_frequency_mean` and `random_frequency_stddev`, and can will use `random_frequency_min` and `random_frequency_max` when provided
Tests
Closes #551 (Along with #550, which is already merged) and closes #559

Random sink frequency

---

.github/workflows/build_test.yml
CHANGELOG.rst
src/sink_tests.cc
src/storage.cc
src/storage.h
src/storage_tests.cc
src/storage_tests.h

Requires [cyclus#1634](https://github.com/cyclus/cyclus/pull/1634) to be merged first! (merged 1/17/24). Note that [cyclus#1634](https://github.com/cyclus/cyclus/pull/1634) breaks cycamore storage because it changes the active dormant API. **Until this PR is merged, the current cycamore/main storage archetype will not work with cyclus/main!**
Closes #553 and #555 
This PR makes the full range of fixed and random active and dormant and size buying behaviors available to Storage. To do so, it introduces a type and five numeric values each for the active frequency, dormant frequency, and request size (18 new parameters total).
Testing included

implement random a/d buypol in storage

---

CHANGELOG.rst
src/storage.cc
src/storage.h
src/storage_tests.cc

Relies on Cyclus PR [cyclus#1646](https://github.com/cyclus/cyclus/pull/1646). Until that one is merged, this one cannot be merged. They should be merged together if possible
This PR implements the new `TotalInvTracker` from [cyclus#1646](https://github.com/cyclus/cyclus/pull/1646) into Storage, which provides an agent-wide inventory limitation and is required as part of initializing the buy policy.
This fixes the janky way that Storage was previously calculating an agent-wide limitation! Now, the `max_inv_size` is applied to the whole facility through the use of `TotalInvTracker`. Closes #554, Storage no longer needs to change the capacity of Resource Buffers ever time step
This also adds two variables 
- `reorder_point` when total facility inventory is above this point, no new demands …

Applies TotalInvTracker and (R,Q)/(s,S) inventory policies to storage

---

.github/workflows/build_test.yml
.github/workflows/build_test_publish.yml
.github/workflows/changelog_test.yml
.github/workflows/publish_latest.yml
.github/workflows/publish_release.yml
CHANGELOG.rst
docker/Dockerfile

This PR should be considered in conjunction with cyclus PR [#1637](https://github.com/cyclus/cyclus/pull/1637).
The main changes being made are converting CI workflows to use [docker/build-push-action](https://github.com/docker/build-push-action) to build and test cycamore (and downstream cymetric) using the Dockerfiles we maintain. 
Some notes:
- the Dockerfile now takes a build argument to specify the tag of the cyclus image to build from
- we use our ghcr registry as a cache backend, such that cached layers are located at <image name>:ci-layer-cache
- we also use ghcr to store images produced from workflow runs, located at <image name>:ci-image-cache.  This allows us to build downstream projects from a unique cycamore image (which is specified by digest in the workflow)
- I added a …

CI refactoring

---

.github/workflows/publish_release.yml
CHANGELOG.rst

`${{ github.ref_name }}` does not exist in the context of a workflow triggered by a release

Update version_tag in `publish_release.yml`

---

.github/workflows/build_test.yml
.github/workflows/pr_comment.yml
.github/workflows/publish_latest.yml
.github/workflows/publish_release.yml
CHANGELOG.rst

Any images are now pushed to the ghcr of `github.repository_owner` instead of cyclus to prevent 403 forbidden errors when PRs originate from forks. 
Also modifies the PR comment implementation to use a separate workflow - also to prevent permissions errors when PRs originate from forks.

Fix CI Refactor

---

.github/workflows/build_test.yml
.github/workflows/publish_latest.yml
.github/workflows/publish_release.yml
CHANGELOG.rst
docker/Dockerfile

Incorporates same updates as cymetric PR [#195](https://github.com/cyclus/cymetric/pull/195)

More CI updates

---

CHANGELOG.rst
src/CMakeLists.txt
tests/CMakeLists.txt

Closes #476.  CMake wasn't rebuilding on a change to the test files because the `cyclus_unit_tests` target doesn't reference the source files directly - we use the `UseCyclus` macro to handle a lot of the cycamore build and "return" env vars holding build info.  
This forces cmake to rebuild the `test/` directory when one of the test files changes.
I'm no CMake expert... if someone knows a better way to handle this please let me know.

Rebuild when test file changes

---

CHANGELOG.rst
src/storage.h

I had a messy merge when finalizing #574, and somehow the old fixed-integer `active_buying` and `dormant_buying` parameters stuck around in the storage header. They're unused and now I removed them to avoid confusion

Old active dormant parameters hanging around in storage

---

.github/workflows/build_test.yml
.github/workflows/pr_comment.yml
CHANGELOG.rst

The PR comment for downstream testing statuses is updated with each successive build.  This PR adds the commit hash that generated the statuses to the comment.

Add commit hash to PR comment

---

CHANGELOG.rst
CONTRIBUTING.rst
DEPENDENCIES.rst
INSTALL.rst
README.rst

The biggest changes are `master` to `main`.  I also updated the Ubuntu versions and changed the links to point to our GitHub releases.  
The minimum required Cyclus version will need to be updated again when we issue the new release.
I will make a separate PR for documenting our container images as an installation option.

Documentation Update

---

CHANGELOG.rst
CMakeLists.txt

Updates the C++ standard required by the compiler.  This is provoked by https://github.com/cyclus/cyclus/pull/1738 but should be done anyway in my opinion since we require C++17 in cyclus/cyclus.

Require C++17 standard in cycamore

---

CHANGELOG.rst
tests/test_regression.py

In a handful of places the method being used to skip tests is different than the standard method (`skip_if_dont_allow_milps()`).  This has not been tested in CI since we always install cyclus and cycamore with the `--allow-milps` flag and COIN.  I tested this locally to confirm that the correct tests are now skipped when cyclus and cycamore are installed without MILPS support - I encourage any reviewers to test locally as well
If we wish to hold this back until CI is in place to test, that is fine with me.  Currently all of our distribution methods build cyclus and cycamore with COIN support so this might not be super pressing

Update newer test classes to skip if cyclus does not have COIN

---

CHANGELOG.rst
INSTALL.rst
README.rst
docker/Dockerfile
install.py
tests/README.rst
tests/run_inputs.py.in
tests/test_regression.py

We used to require a version agnostic `python` in the environment.  This removes that necessity and refers to `python3` instead

Use `python3` instead of `python` in environment

---

CHANGELOG.rst
src/storage.cc

A small change to allow for the removal of the `ResourceBuff` class in cyclus

Deprecate `ResourceBuff`

---

CHANGELOG.rst
CMakeLists.txt

This change was implemented in cyclus already in https://github.com/cyclus/cyclus/pull/1748.  It resolves issues with linking in a conda-forge feedstock, and issues with linking on MacOS.

Link against `libxml++` imported target 

---

CHANGELOG.rst
src/enrichment.cc
src/enrichment_tests.cc
src/fuel_fab.cc
src/fuel_fab_tests.cc
src/mixer.cc
src/mixer_tests.cc
src/reactor.cc
src/separations.cc
src/separations_tests.cc
src/sink.cc
src/sink_tests.cc
src/source.cc
src/source_tests.cc

Clean up `using cyclus::` declarations

---

CHANGELOG.rst
src/storage.cc
src/storage.h
src/storage_tests.cc
src/storage_tests.h

Must come after cyclus [PR#1749](https://github.com/cyclus/cyclus/pull/1749)
Closes #552

Add packaging to storage

---

CHANGELOG.rst
src/storage_tests.cc

The order of packaged material isn't guaranteed. When checking resources going through packaging, need to check them as a vector and not as exact order. This PR updates the affected tests.
This is also being changed in cyclus tests, in [cyclus#1750](https://github.com/cyclus/cyclus/pull/1750).
Closes #611

cannot assume order of packaged material

---

CHANGELOG.rst
src/source.cc
src/source.h
src/source_tests.cc
src/source_tests.h

Adds the ability for source to provide materials that are packaged.
Along the way, I also converted Source to a ResBuf facility. This means that the full inventory is created at the `EnterNotify` step and placed into the inventory buffer, then persists throughout the simulation. Previously, material never existed until the moment it was about to be traded, when it would be created. Source just maintained a number that represented the inventory at hand.
This change is generally minor, but it makes packaging easier. Without pre-existing resources in a buffer, trades would be executed by created materials, trying to package them, and then in the rare case where the trade has some leftover material that can't be packaged (rare, and specifically only exists in cases where the requesting agent …

Source can package 

---

CHANGELOG.rst
src/source_tests.cc

I figured out why tests in #613 failed. After playing with it a bit, I kept getting results where the number of packaged resources was twice the number of transactions, which didn't make sense (every packaged resource should only be packaged in order to fulfill one transaction). 
Then I realized that my tests didn't include an outrecipe, and the Mock Sink in the Mock Sim was for some reason requesting a different mock composition. So, immediately before trading, the Source transmuted the composition to the request composition, which creates a new line in the resource table, because the composition id (QualId I think) changed. 
This is exactly the kind of extra and confusing resource database entries I mentioned above!
However, I still think it makes sense that resource should only be …

add recipes to source packaging tests to avoid undesired transmutation

---

CHANGELOG.rst
src/storage.cc
src/storage.h
src/storage_tests.cc

Adds a new parameter to Storage to take advantage of the transport unit capability in the material sell policy.
Closes #557

Adding transport units to Storage

---

CHANGELOG.rst
src/reactor.cc
src/reactor.h
src/sink.cc
src/sink.h

Reactor and sink keep packaging

---

CHANGELOG.rst
src/reactor.h
src/sink.h

default needs to be `True` not `true` for cycamore to build

Fix error in keep_packaging defaults

---

CHANGELOG.rst
src/source.cc

`n_full_bids` could result in negative int max when `bid_qty` = 0, when it should be zero
~~Requires [cyclus#1790](https://github.com/cyclus/cyclus/pull/1790) to be merged first!~~ (merged)

prevent underflow when not enough material is available to make a packagable bid

---

CHANGELOG.rst
src/source.cc
src/source.h
src/source_tests.cc

Source move inv resource creation to Build from EnterNotify

---

CHANGELOG.rst
src/source.cc

Source prevent seg fault due to packaging failure

---

CHANGELOG.rst
src/source.cc

Must be merged after [cyclus#1813](https://github.com/cyclus/cyclus/pull/1813). Tests on latest should be re-run and should pass after that's merged

update call to Package::GetFillMass

---

CHANGELOG.rst
src/storage.cc

The only thing that shows up in my terminal when I run simulations with verbosity 2 is the time step... and a single logging function in Storage, `Storage prototype() moved resources from ready to stocks at t=->time()`.
Moving resources between ResBufs is not a `LEV_INFO1` level of logging, and most (all?) other archetypes don't log anything above `LEV_INFO3`. Changed to a level commensurate with the logging of other ResBuf moves in Storage

movements of resources from ready to stocks is not INFO1 importance

---

CHANGELOG.rst
src/cycamore.h

Partially addresses https://github.com/cyclus/cyclus.github.com/issues/389 in conjunction with https://github.com/cyclus/cyclus/pull/1815

Add link to fuelcycle.org to doxygen homepage

---

CHANGELOG.rst
CMakeLists.txt

I was working on the cycamore_dev conda build and it demonstrated to me that we don't actually need Libxml++ to build cycamore.  This PR removes it as a CMake build requirement

Remove Libxml++ requirement from build

---

CHANGELOG.rst
src/storage.cc
src/storage.h
src/storage_tests.cc

Adds the ability to use a binomial distribution to active and dormant cycles which requires one parameter, the probability that any individual time step would end the current cycle. This is specifically useful for disruption modeling, where you can assume that at every time step there is some very small chance that the agent goes offline (i.e. dormant) and vice versa for dormant.
This is a negative binomial distribution (since we're sampling the number of trials until n successes, rather than sampling the successes in n trials), in the specific case where the number of successes is always one. This is equal to a geometric distribution, but since negative binomial is more generic that's what is implemented in [cyclus#1841](https://github.com/cyclus/cyclus/pull/1821) and used here. Note …

support for binomial active/dormant in storage

---

CHANGELOG.rst
CMakeLists.txt

Adds a `-DBOOST_VERSION_MINOR` definition to support changes in https://github.com/cyclus/cyclus/pull/1792.

Support Boost 1.86

---

CHANGELOG.rst
src/CMakeLists.txt
src/conversion.cc
src/conversion.h

Cycamore lacks a facility labeled "Conversion", which is a little confusing when you're trying to build out a whole fuel cycle model out of Cycamore. You CAN use other facilities to emulate a conversion facility (they're pretty simple), but that's not totally obvious how to do, and so I thought it might be nice to just add one.
This PR is related to:
- Closes #646 
None
I used making this facility as a way to vet an "advanced cyclus agent development" tutorial I've been working on, and so that's why I defined the DRE functions manually instead of using the toolkit. It was good practice, since I've done it the other way (and also my tutorial worked great btw).
I don't have any tests for this yet, since I wanted to run it by people first before I spent time on the not-so-fun parts of Agent …

Add Conversion Facility to Cycamore
