- tests/input/dynamic_capacitated.xml
companion to ~~cyclus/cyclus#1084~~ cyclus/cyclus#1085
> fixes dynamic capacitated tests to assume start+life-1 decommissioning

- src/CMakeLists.txt
- src/fuel_fab.cc
- src/fuel_fab.h
- src/fuel_fab_tests.cc
Blocked on cyclus/cyclus#1084 - surprise!
> Fuel fab is ready

- input/enrichment/1_src_enr_rxtr_sink.xml
- input/enrichment/linear_src_enr_rxtr_sink.xml
- input/enrichment/natu_capacitated.xml
- input/enrichment/swu_capacitated.xml
- input/minimal-input/source_1_lifetime_sink_1.xml
- input/minimal-input/source_1_sink_1.xml
- input/minimal-input/source_3_lifetime_sink_1.xml
- input/minimal-input/source_3_sink_1.xml
- input/physor/2_Sources_3_Reactors.xml
- src/source.cc
- src/source.h
- src/source_tests.cc
- src/source_tests.h
- tests/input/growth.xml
Note one test removal - this is either because the code that was being tested was unnecessary and removed, or the test is redundant with regression tests.  Some MockSim style tests might be nice when someone has time - we can create an issue for that - or someone can PR into this PR.
> generalizing and finalizing source for 1.3

- tests/input/dynamic_capacitated.xml
- tests/test_regression.py
updates tests for using only cycamore sources and sinks
> rm'd use of source and sink from agent lib in tests

- .gitignore
- input/recycle.xml
- recycle.xml
- src/CMakeLists.txt
- src/separations.cc
- src/separations.h
- src/separations_tests.cc
- tests/test_regression.py
It still needs a bit more doc/annotations and tests.
> new separations facility

- input/growth/source_sink_linear.xml
could @rwcarlsen, @mbmcgarry, @opotowsky, or @vcloitre look at this at their earliest convenience, please?
> fixes input file for new source schema

- tests/CMakeLists.txt
- tests/run_inputs.py.in
- tests/test_run_inputs.py
this fixes run_inputs in cmake and adds running it as a test. Please try it out and let me know if the tests take too much time. At the least, we should fix the cmake issue.
> Run inputs

- src/fuel_fab.h
- src/separations.h
> Revert "adding niches for fab and sep"

- src/fuel_fab.cc
- src/fuel_fab_tests.cc
> fix fuel fab buffer composition assumption bug

- src/fuel_fab.h
- src/separations.h
same pr from before, different commit. sorry for the gymnastics here @FlanFlanagan. Can you give this another quick glance over please.
> niche for fuel fab and separations

- src/deploy_inst.h
- src/reactor.h
Same as before - just PR in the right branch.
> Fix uitype typo

- src/sink.h
matching sink docs to source docs
> sink docs match source docs, fixes #344

- src/deploy_inst.h
- src/enrichment_facility.h
- src/fuel_fab.h
- src/growth_region.h
- src/manager_inst.h
- src/reactor.h
- src/separations.h
- src/sink.h
- src/source.h
This is a review of cycamore archetypes intended to increase the use of uilabels both to make the UI experience better when using these archetypes and to better demonstrate capability to future archetype developers.
> Add more UI support to Cycamore archetypes

- src/sink.h
hotfix for sink using resource buf
> deprecate sink's use of resource buffer

- src/fuel_fab.cc
related to cyclus/cyclus.github.com:#149 and #355
> adding exp warning to fuelfab

- install.py
> adding config only option

- install.py
Pretty minor and I have tested it on my machine.
> uninstall typo fixes

- CMakeLists.txt
Also with a check for support and a message if missing.
> add c++11 flags

- README.rst
> fix broken/old readme links.

- .gitignore
- input/greedy_recycle.xml
- input/physor/1_Enrichment_2_Reactor.xml
- input/physor/2_Sources_3_Reactors.xml
- input/physor/greedy_1_Enrichment_2_Reactor.xml
- input/physor/greedy_2_Sources_3_Reactors.xml
- input/recycle.xml
- src/enrichment.cc
- tests/input/dynamic_capacitated.xml
- tests/input/growth.xml
- tests/test_regression.py
This PR updates all tested input files to use the COIN solvers. I found this helpful in debugging coin-related issues, so I propose to include it for future developers who happen to work on the mathematical programming side to provide evidence of non-trivial bugs.
> Coinsolvers

- src/mixer.cc
correct a incorrect warning (issue #404)
> warning correction

- src/fuel_fab.cc
add a warning when the `fuel_fab` is not able to reply to a request because of weight values
> wrning in fuel_fab

- tests/test_regression.py
> removing usage of deprecated unittest

- conda-recipe/post-link.sh
- install.py
These are the same improvements as cyclus/cyclus#1214
> Recipe improvements

- cmake/FindCyclus.cmake
- install.py
This allows me to build, install, and test with conda.
> Update Build to be in line with Cyclus

- INSTALL.rst
same as the cyclus one, add some flag to automatically hook the installation part and include it into fuel cycle.org website....
same as the PR https://github.com/cyclus/cyclus/pull/1295
> adding flag in install

- AUTHORS.rst
- CONTRIBUTING.rst
- DEPENDENCIES.rst
- LICENSE.rst
- README.rst
This PR will break the `install_docs_rework` branch of cyclus.github.com until 
https://github.com/cyclus/cyclus.github.com/pull/216 is merged
> Pphw dox rev2

- INSTALL.rst
- README.rst
Small changes to fix Sphinx warnings when building into website
> Sphinx warning

- src/sink.h
- src/source.h
- src/storage.h
Edited source, sink, and storage to include range uitype for non-negatives state variables. Storage pref incommodities edited to include positive range.
> updated metadata

- src/sink.h
This fixes the current build problems for me
> gotta watch those newlines

- DEPENDENCIES.rst
this is suppose to update the DEPENDENCIES doc, which a little bit  is broken..
I don't know how I am supposed to submit it so I just PR it...
> Master doc update

- CONTRIBUTING.rst
- README.rst
- circle.yml
> migration changes from develop to master

- Dockerfile
removing un-required symlink that is actually blocking the deploy script
> fix deploy

- src/reactor.cc
This adds a time series tracker for used fuel from the reactor
> Added TimeSeriesUsedFuel

- src/enrichment.cc
> ID to AgentId

- src/separations.cc
> Separations clarification

- src/separations.cc
This PR adds `RecordTimeSeries` for the Separations facility.
> Recordtimeseries separations

- src/storage.cc
this PR contains implementation of `RecordTimeSeries` for the storage facility.
> Recordtimeseries storage

- news/decom_reactor.rst
- src/reactor.cc
This has the reactor decommission itself as soon as it is out of fuel and spent fuel.
> reactor decom

- src/enrichment.h
- src/sink.cc
Replaced references to month when it should be generic timestep for clarity
> remove references to month when it should be timestep

- CHANGELOG.rst
- CONTRIBUTING.rst
This PR updates the CONTRIBUTING document for the Cycamore repo, based on changes made to the same document in the Cyclus repo: https://github.com/cyclus/cyclus/pull/1882.
> Update CONTRIBUTING Guidelines
